version: "3.9"

services:
  backend:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "3030:3030"
    container_name: backend
    restart: unless-stopped
    volumes:
      - ./server:/app
    networks:
      ollosa_network:
        ipv4_address: 192.168.1.2
    volumes:
      - ./client/dist:/var/www/html

  frontend:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "4173:4173"
    container_name: frontend
    restart: unless-stopped
    depends_on:
      - backend
    networks:
      ollosa_network:
        ipv4_address: 192.168.1.3

  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "8080:8080"
      - "443:443"
    volumes:
      - ./nginx:/etc/nginx/conf.d
      - ./ssl:/etc/ssl/certs/
      - ./client/dist:/var/www/html
    networks:
      ollosa_network:
        ipv4_address: 192.168.1.4
    depends_on:
      - frontend
      - backend

networks:
  ollosa_network:
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.1.0/24
