version: "3.9"

services:
  backend:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "3030:3030"
    container_name: backend
    restart: unless-stopped
    volumes:
      - ./server:/app
    networks:
      ollosa_network:
        ipv4_address: 192.168.1.2

  frontend:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "3050:3050"
    container_name: frontend
    restart: unless-stopped
    depends_on:
      - backend
    networks:
      ollosa_network:
        ipv4_address: 192.168.1.3

networks:
  ollosa_network:
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.1.0/24
